import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import { AppProvider } from "./context/useAuth";

export const metadata: Metadata = {
  title: "Suostei",
  description: "Generated by suostei team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#eee]">
        <AppProvider>
          <Providers>
            <Navbar />
            <main className="container mx-auto px-36 py-6">{children}</main>
          </Providers>
        </AppProvider>
      </body>
    </html>
  );
}
